name: car_club_rocknrome
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  http: ^1.2.1
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  intl: ^0.17.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mercedes_green.png
    - assets/git-logo.png
    - assets/li-logo.png
